version: '2'
services:
    web_nginx:
        build:
            context: ./
            dockerfile: ./nginx/Dockerfile
        volumes:
            - ./laravel:/var/www
        ports:
            - "80:80"
        links:
            - app
    app:
        build:
            context: ./
            dockerfile: ./laravel-backend/Dockerfile
        volumes:
            - ./laravel-backend:/var/www
        links:
            - shoppingcartdb
            - cache
        environment:
            - "DB_PORT=3306"
            - "DB_HOST=mysql"
            - "REDIS_PORT=6379"
            - "REDIS_HOST=cache"
        ports:
            - "9000:9000"
    shoppingcartdb:
        image: postgres
        environment:
          POSTGRES_PASSWORD: root
          POSTGRES_USER: root
        volumes:
          - ./postgres/data:/var/lib/postgresql/data:Z
        ports:
          - "5432:5432"
    adminer:
        image: adminer
        restart: always
        ports:
          - "8080:8080"
    cache:
        image: redis:3.0
        ports:
            - "63791:6379"
    #mysql:
    #    image: mysql
    #    environment:
    #      MYSQL_ROOT_PASSWORD: root
    #      MYSQL_DATABASE: shoppingcart
    #    ports:
    #      - "3306:3306"
    #    user: "1000"
    #    volumes:
    #      - ./db/mysql:/var/lib/mysql


